services:
  api:
    build: ./api
    dockerfile : Dockerfile
  depends_on:
    db:
    condition : service_healthy
    restart : true
    environment:
      - APPLICATION_ENVIRONMENT=${APPLICATION_ENVIRONMENT}
    networks:
      -internal_network

  app:
  build:
    context : ./
    dockerfile : Dockerfile
    depends_on:
      -api
    ports:
      -80:80
    networks:
      -internal_network
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      -pgdata:/var/lib/postgresql/data
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}","-d","${POSTGRES_DB}"]
      interval: 10s
      retries : 5
      
volumes:
  pgdata:
networks:
  internal networks:
    driver: bridge
